server:
  port: 0
spring:
  application:
    name: account-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9000
          jwk-set-uri: http://auth-service:9000/.well-known/jwks.json
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    root: INFO
