server:
  port: 9000
spring:
  application:
    name: auth-service
  sleuth:
    sampler:
      probability: 1.0
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-service:9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    root: INFO
