spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
